services:
  - type: web
    name: sentiq-ai-backend
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: ENCRYPTION_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: GOOGLE_REDIRECT_URI
        sync: false
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "43200"
      - key: ALLOWED_ORIGINS
        value: "https://sentiq-ai.vercel.app,http://localhost:5173"
